import { ITestimonials } from '@/interfaces/i-testimonials';

export const testimonials: Array<ITestimonials> = [
  {
    id: 4,
    text: 'Rafal has really helped me to get back to the gym, stay consistent with my trainings, and take care of my body. Rafal understands my physical strengths and weaknesses and tailors my workouts to challenge me and avoid injuring areas where I am building strength. The workouts are both rigorous, but also enjoyable for me. I look for to meeting up with Rafal for my trainings which has kept me coming back to the gym more consistently than ever. I highly recommend Rafal to anyone who is seeking a knowledgeable and attentive personal trainer.',
    name: 'Dave',
    position: 'Zawód',
    picture: './images/4.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 5,
    text: 'Rafal to profesjonalista. Z tym trenerem nie trzeba się obawiać monotonnych treningów – są urozmaicone, ciekawe i skuteczne. Atmosfera treningu jest przyjacielska i sympatyczna ale nie lekka. Daje wycisk :)',
    name: 'Dominik',
    position: 'Zawód',
    picture: './images/5.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 6,
    text: 'Trenujemy z Rafałem od września 2016 roku. Moc, energia, forma, rzeźba. Polecam ale trzeba się przygotować na prawdziwy trening 😄💪🏼💪🏼💪🏼',
    name: 'Piotr',
    position: 'Zawód',
    picture: './images/6.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 7,
    text: 'Rafał dobiera ćwiczenia do trybu życia i możliwości ćwiczącego. Ćwiczenia są bardzo różnorodne, a do tego Rafał jest sympatycznym i ciekawym gościem więc nie można się nudzić :) Potrafi też zmotywować żeby na treningu dać z siebie wszystko. Zdecydowanie polecam treningi z Rafałem!',
    name: 'Mateusz',
    position: 'Zawód',
    picture: './images/7.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 8,
    text: 'Treningi z Rafałem to ciągłe podnoszenie poprzeczki, nowe wyzwania i mnóstwo radości! Rafał  jest perfekcyjne przygotowany merytoryczne, śledzi nowe trendy w fitnessie i ma dużą wiedzę o odżywianiu. Pilnuje poprawności wykonywanych ćwiczeń, doradza przy planowaniu posiłków, ale przede wszystkim niesamowicie motywuje do dawania z siebie jak najwięcej. Treningi z Rafałem polecam każdemu!',
    name: 'Ania',
    position: 'Zawód',
    picture: './images/8.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 9,
    text: 'Ćwiczę już z Rafałem od ponad 1 roku i jestem bardzo zadowolony z efektów. Rafał jest zawsze bardzo profesjonalny, słowny i co najważniejsze - posiada bardzo dużą wiedzę z tematów związanych ze sportem i zdrowiem. Każdy trening odbywa się w miłej atmosferze z dużą dawką humoru i śmiechu, co mnie dodatkowo motywuje i sprawiło, że nigdy nie opuściłem żadnego treningu z Rafałem. Szczerze polecam!',
    name: 'Michał',
    position: 'Zawód',
    picture: './images/9.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 10,
    text: 'Rafał to profesjonalny trener - nie ma dla niego rzeczy niemożliwych do osiągnięcia.',
    name: 'Mariusz',
    position: 'Zawód',
    picture: './images/10.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 11,
    text: 'Zdecydowanie polecam Rafała, jest przede wszystkim specjalista z ukończonymi studiami, i stałe rozwijającym się w swoje branży. Holistyczne podejście i nie tylko wieków ciężary ale i wiele różnorakich ćwiczeń. Mega wiedza i świetny kontakt, zdecydowanie polecam !!!!!',
    name: 'Łukasz',
    position: 'Zawód',
    picture: './images/11.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 12,
    text: 'Trening z Rafałem zaczęliśmy od wywiadu “środowiskowego”, rozmowa była nakierowana na poznanie mojej przeszłości w kontekście aktywności fizycznej, stylowi życia oraz ewentualnych urazów. Następnie przeszliśmy do zarysowania celi i sprawdzeniu obecnych możliwości, wszystko przebiegało w bardzo swobodnej atmosferze. Jako początkującemu (zasiedziały biurowy 30latek) bardzo zależało mi aby trener zwracał uwagę na poprawność postawy oraz wykonywanych ćwiczeń, co robi na każdych zajęciach i cały czas stara się przyglądać i korygować niepoprawnie wykonywane powtórzenia. Dodatkowo, do tej pory praktycznie żadne zajęcia nie miały tych samych ćwiczeń, oprócz standardowych sztang, maszyn, etc. korzystamy z worków bułgarskich, różnych piłek, gum, pełna różnorodność uruchamiająca wszystkie partie mięśni, co bardzo mi odpowiada. Jestem na początku swojej drogi, ale z pewnością mogę Rafała polecić!',
    name: 'Jan',
    position: 'Zawód',
    picture: './images/12.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 13,
    text: 'Poszukiwania idealnego trenera nie były łatwe miałam jednak wielkie szczęście spotkać Rafała. Dla mnie przede wszystkim najważniejszy był powrót do poprawnej postawy ciała i zakończeniu coraz częstszych problemów z plecami czy  obręczą barkową. Od momentu rozpoczęcia treningu dolegliwości zdecydowanie się zmniejszyły. Jest to mój początek treningów ale wreszcie widzę możliwość wyjścia z problemów bólowych. Wszystkie ćwiczenia ułożone są  do indywidualnych potrzeb, Rafał objaśnia dokładnie na czym polega ćwiczenia i jaki ma cel, dodatkowo pomaga w ułożeniu ćwiczeń które można swobodnie powtórzyć w domu- podsumowując serdeczny, pomocny trener z ogromna wiedzą w obszarze treningu holistycznego.',
    name: 'Ania',
    position: 'Zawód',
    picture: './images/13.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 14,
    text: 'Profesjonalista w każdym calu! Treningi przebiegają w sympatycznej atmosferze i przede wszystkim dają efekty.  Ciężko się do niego dostać, bo   ma więcej chętnych , niż doba ma godzin, ale Rafał zawsze stara się znaleźć rozwiązanie.  Trener godny polecenia.',
    name: 'Imię',
    position: 'Zawód',
    picture: './images/14.jpg',
    date: 'styczeń, 2020',
  },
];

export const testimonials2: Array<ITestimonials> = [
  {
    id: 1,
    text: 'Pełen profesjonalizm i zaangażowanie pracą z klientem. Przemiłe usposobienie i świetne podejście do treningu. Gorąco polecam.',
    name: 'Maciej',
    position: 'Pozycja',
    picture: './images/1.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 2,
    text: 'Rafała lubię i polecam każdemu leniwcowi. Wcześniej nie rozumiałam, po co ludzie chodzą do trenerów personalnych, wydawało mi się, że można ćwiczyć samemu przecież. No nie można, bo po pierwsze nie znamy się na tych wszystkich mięśniach, przeciążeniach itp., a po drugie nie ma nic lepszego jak ,,żywy bat" nad ćwiczącym. A jeśli ten ,,żywy bat" jest jeszcze miły, uśmiechnięty i ma ogromne poczucie humoru, to ćwiczenia są przyjemnością. Rafał jest też po prostu fajnym kolegą. Polecam!',
    name: 'Agnieszka',
    position: 'Zawód',
    picture: './images/2.jpg',
    date: 'styczeń, 2020',
  },
  {
    id: 3,
    text: 'Jako nieaktywna fizycznie 28 latka, pracująca przy biurku i z dużą nadwagą, postanowiłam wziąć się za siebie i zacząć trenować na siłowni. Zależało mi na tym, żeby schudnąć, ale jednocześnie chciałam ćwiczyć bezpiecznie i prawidłowo technicznie. Oczywistą sprawą było, że potrzebuje pomocy profesjonalisty - internet i dobre opinie skierowały mnie do Rafała. Ćwiczyliśmy razem rok. Po tym czasie mogę stwierdzić z pełnym przekonaniem, że Rafał nie tylko bardzo dobrze zna się na tym, co robi, ale treningi z nim to czysta przyjemność. Potrafi bardzo dobrze zmotywować do wysiłku, ale też zarazić tą pasją. Każdemu kto zastanawia się czy warto - gorąco polecam.',
    name: 'Kasia',
    position: 'Zawód',
    picture: './images/3.jpg',
    date: 'styczeń, 2020',
  },
];
